### PR TITLE
bugfix: Fix alibabacloud storageclass config

### PR DESCRIPTION
**Pull request by mowangdk**
Correct Alibaba Cloud CSI storage class configuration

### CODE REVIEW

**Comment by noctarius** [comment]
Awesome, thanks :)

**Comment by noctarius** [comment]
Btw, which features does the NAS CSI support? At the moment only dynamic is mentioned which means everything else is assumed false. Is it the same features as for the disk CSI? Same question for the Oss CSI.

**Comment by mowangdk** [comment]
> Btw, which features does the NAS CSI support? At the moment only dynamic is mentioned which means everything else is assumed false. Is it the same features as for the disk CSI? Same question for the Oss CSI.

I'll fill up the details about NAS & OSS later with another PR

**Comment by noctarius** [comment]
> I'll fill up the details about NAS & OSS later with another PR

Awesome! Thanks a lot. I hope I can get this list as complete and accurate as possible 🙏

**Pull request merged**
